### ISSUE TITLE
Normalize the 'start point' too!

### ISSUE THREAD

**Issue by oetiker** [wadefagen/91-DIVOC#2]
Great work! Thank you!

When normalizing by Country, could you also 'normalize' the 100-cases starting point?  This would probably get rid of a lot of the vertical shift between the curves. Even though it sais so at the bottom of the chart, the data does not look as if it was normalized in that way.

https://github.com/wadefagen/91-DIVOC/blob/f780d123fcfce346cba8a28f63030f80e2506711/pages/covid-visualization/index.html#L149

**Comment by wadefagen** [comment]
What would you propose for a "normalized" start point?  The graph starts at 1 case /1,000,000 people -- though some countries start at, for example, 1.453 cases /1,000,000 people and their first data point will be (0, 1.453).

In that case, the dotted line could start at (0, 1.453) and grow at a 35% daily rate from that starting point -- but then a second country, for example (0, 1.001) that passes the 1 case/1m threshold the same day, will be below the line.

The data could certainly be "normalized again" so that (0, 1) is always the "double normalized" starting point, but you are losing data interpretability and I think, particularly for data as important as this, interpretability is the most important thing.

**Comment by oetiker** [comment]
I am from Switzerland, and in your chart, Switzerland starts off with 2.096 on day 0 ... the effect I guess is more pronounced with smaller countries ... if you look at https://www.corona-data.ch/ they set the start for their data to  0.4 cases in  10'000 people and it seems to work quite well ...
