### ISSUE TITLE
California New Deaths/Day is missing from "COVID-19 Cases by US States/Territories, normalized by population"

### ISSUE THREAD

**Issue by joyjit** [wadefagen/91-DIVOC#21]
In the chart titled "COVID-19 Cases by US States/Territories, normalized by population"

"California" is missing from the dropdown list, if I try to choose "New Deaths/Day"

California comes back for other items

**Comment by wadefagen** [comment]
Thanks for the bug report! I didn't keep up with the issues page and, instead, focused on e-mail, but now using better practices and running it much more via git.

This was due to California, at that time, not reaching the threshold for displaying the data.  Soon after your comment, I added a message at the bottom to explain that to avoid the confusion.  Unfortunately, I wish it was still not showing -- but instead here is the latest for CA: https://91-divoc.com/pages/covid-visualization/?chart=states&highlight=California&show=us-states&y=both&scale=linear&data=cases-daily-7&data-source=jhu&xaxis=right#states 😢
