### ISSUE TITLE
Feature request: smoothing for per day numbers

### ISSUE THREAD

**Issue by itsallonetome** [wadefagen/91-DIVOC#27]
Either add a selection for smoothing, or add a smoothed line to the selected country's display.

This is especially important for the "per day" statistics as delays / inefficiencies in the stats flow to central publishers means sawtooth graphs: low number one day followed by high number the next.  All artefacts of the stats collection process not the "real" situation.

**Comment by jetojedno** [comment]
Thanks.  The regression lines are a good proxy for smoothing. :-)

My only question is the algorithm: it looks to me like the regression line has been taken using solely the first and last points in the range, rather than all the points.  Using all the points results in a more stable forecast line.
There's a package here: https://github.com/Tom-Alexander/regression-js which gives a good exponential regression line calc.  Exponential regression is, I believe, correct for geometric growth.

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github, sorry for missing this!

The trendlines were removed soon after this and a "daily" and "7-day averaged" selection was added for all data options.  For example, here's the United States new cases/day, as a 7-day average: https://91-divoc.com/pages/covid-visualization/?chart=countries&highlight=United%20States&show=25&y=both&scale=linear&data=cases-daily-7&data-source=jhu&xaxis=left#countries
