### ISSUE TITLE
Switzerland is missing from population-normalized graph

### ISSUE THREAD

**Issue by danmackinlay** [wadefagen/91-DIVOC#28]
In the third graph "COVID-19 Cases by Country, normalized by country population", Switzerland is missing from the country-highlight dropdown

**Comment by wadefagen** [comment]
Thanks for the bug report! I didn't keep up with the issues page and, instead, focused on e-mail, but now using better practices and running it much more via git.

This was due to Switzerland, at that time, not reaching the threshold for displaying the data. Soon after your comment, I added a message at the bottom to explain that to avoid the confusion. Unfortunately, the cases reached the 1 case/1m threshold and now visible: https://91-divoc.com/pages/covid-visualization/?chart=countries-normalized&highlight=Switzerland&show=25&y=highlight&scale=linear&data=cases-daily-7&data-source=jhu&xaxis=left#countries-normalized
