### ISSUE TITLE
Daily Test Positivity 1-week average shows the average of the last 7 percentages, not the true average positivity rate

### ISSUE THREAD

**Issue by joeledvina** [wadefagen/91-DIVOC#47]
Being in Arkansas, I noticed the 7-day test positivity averages seemed too high compared to the daily total tests and positive results. It appears that the state sometimes reports low numbers of tests with high or even 100% positive results, and this is skewing the 7-day average. It appears that the chart is averaging the last 7 percentages, regardless of the numbers of tests, so the days with 100% positive results on a lower number of tests is pulling the average far higher. The 7-day average of of this ratio should instead sum the number of positive tests over the last 7 days and divide by the total number of tests over the last 7 days.

**Comment by skids** [comment]
I think it's a slightly different problem.  Look at Nevada for example.  It looks to me like the 7 day average is averaging the numbers from the cumulative positivity rate chart rather than the daily chart.  It may or may not be correctly weighting by the "number of tests" from that chart... we wouldn't be able to tell because there is not much proportional movement in the cumulative number of tests... it's taking the numbers from the wrong data chart to begin with.

Nevada's last 7 days on the cumulative chart, divided by 7:

```
$ perl -e 'print ((5.66 + 5.6 + 5.53 + 5.5 + 5.45 + 5.47 + 5.45)/7)'
5.52285714285714
```
...and that matches the most recent value on the 7-day average chart.

On the daily chart the values are:

```
$ perl -e 'print ((4.63 + 6.39 + 3.41 + 4.53 + 3.84 + 3.21 + 3.84)/7)'
4.26428571428571
```
...so that's what it would be if it were happening as orginally described.

It should be (using the normalized numbers, it shouldn't matter):

```
$ perl -e 'print ((4.63*1212.3 + 6.39*1164.2 + 3.41*1398 + 4.53*1274 + 3.84*1828.9 + 3.21*1520.7 + 3.84*1677.8) / (1212.3 + 1164.2 + 1398 + 1274 + 1828.9 + 1520.7 + 1677.8))'
4.16218521422404
```

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page.  Moving to managing this issues on github, sorry for missing this!

I fixed this soon after you made this comment, and all grpahs has since used the "true" 7-day average for all 7-day statistics on https://91-divoc.com/pages/covid-visualization/ :)
